app:
  title: RHDH Root HTTP Router Middleware Example
  baseUrl: http://${HOSTNAME:-localhost}:7007

backend:
  auth:
    keys:
      - secret: development
  baseUrl: http://${HOSTNAME:-localhost}:7007
  listen:
    host: ${HOSTNAME:-localhost}
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    upgrade-insecure-requests: false
  cors:
    origin: ${BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations: {}

proxy:
  endpoints:
    '/add-test-header': 
      target: http://${HOSTNAME:-localhost}:7007/api/simple-chat
      credentials: forward
      headers:
        'x-proxy-test-header': 'hello!'
auth:
  environment: development  
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    internal.backstage-plugin-simple-chat:
      appIcons:
        - name: chatIcon
          importName: ChatIcon
      dynamicRoutes:
        - path: /simple-chat
          importName: SimpleChatPage
          menuItem:
            text: 'Simple Chat'
            icon: chatIcon